apiVersion: apps/v1
kind: Deployment
metadata:
  name: osd-adoption-metrics-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      name: osd-adoption-metrics-exporter
  template:
    metadata:
      labels:
        name: osd-adoption-metrics-exporter
    spec:
      serviceAccountName: osd-adoption-metrics-exporter
      containers:
        - name: osd-adoption-metrics-exporter
          # Replace this with the built image name
          image: quay.io/anaik/osd-adoption-metrics-exporter:v0.1.3-8ff25f49
          command:
          - osd-adoption-metrics-exporter
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "osd-adoption-metrics-exporter"
