kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: osd-adoption-metrics-exporter
subjects:
- kind: ServiceAccount
  name: osd-adoption-metrics-exporter
roleRef:
  kind: Role
  name: osd-adoption-metrics-exporter
  apiGroup: rbac.authorization.k8s.io
